### ISSUE TITLE
how to check which product I can use my KMS server to active

### ISSUE THREAD

**Issue by VegetableBirdy** [MicrosoftDocs/windowsserverdocs.zh-cn#13]
how to check which product I can use my KMS server to active.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: cc852932-b3f4-25ea-46b1-a9abb93fabac
* Version Independent ID: 5a03c0fc-a460-678d-c2ea-e9b8aeae6a75
* Content: [KMS 故障排除指南](https://docs.microsoft.com/zh-cn/windows-server/get-started/activation-troubleshoot-kms-general#feedback)
* Content Source: [WindowsServerDocs/get-started/activation-troubleshoot-kms-general.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/get-started/activation-troubleshoot-kms-general.md)
* Technology: **server-general**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by srvbpigh** [comment]
Hello, @VegetableBirdy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @VegetableBirdy, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/4233. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
