### ISSUE TITLE
about diskpart cmd

### ISSUE THREAD

**Issue by Hiiam9** [MicrosoftDocs/windowsserverdocs.zh-cn#14]
[在此处输入反馈]
hi，why i use command ：diskpart /s xxx.txt is not run on win10
but i tested on Win Xp it is can run 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bca0f8f7-da0d-6340-bf63-f269be5f64d1
* Version Independent ID: 39758423-e92d-d2db-88f3-260dc5a1a26a
* Content: [DiskPart](https://docs.microsoft.com/zh-cn/windows-server/administration/windows-commands/diskpart)
* Content Source: [WindowsServerDocs/administration/windows-commands/diskpart.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/administration/windows-commands/diskpart.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by srvbpigh** [comment]
Hello, @Hiiam9
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @Hiiam9, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/4243. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
