### ISSUE TITLE
when use git bash as the default shell , copy file to windows failed.

### ISSUE THREAD

**Issue by wwfyde** [MicrosoftDocs/windowsserverdocs.zh-cn#5]
return : /c: /c: Is a directory
two ways : "c/dir/path",  "c:/dir/path"  can't transfer file successfully!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 07417484-bd6d-e6f4-110e-e42c2428a369
* Version Independent ID: 844743a6-f67b-421f-9591-13da36b23b14
* Content: [安装适用于 Windows 的 OpenSSH](https://docs.microsoft.com/zh-cn/windows-server/administration/openssh/openssh_install_firstuse#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by srvbpigh** [comment]
Hello, @wwfyde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @wwfyde 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/3550

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
